### ISSUE TITLE
New rtp channels

### ISSUE THREAD

**Issue by CatBoyTop2008** [RonanPlugins/BetterRTP#201]
**Plugin Version**:
[BetterRTP] Version #3.6.12

**Request**:
Please can you add support for plugins such as worldguard so that players can use a random teleport near other players' bases, and another channel so that players can teleport near other players in the selected world.

**How/Why**:
I think this feature is very cool and will appeal to lot of users!

**Additional Context**:
I will leave you with one plugin that contains an example of what I explained. 
But be careful because there are errors/bugs there!

Check classes here \HolyWorldRtp-2.0.5\me\galtap\holyworldrtp\core\impl 
BaseRtp.class and PlayerRtp.class
[HolyWorldRtp-2.0.5.zip](https://github.com/RonanPlugins/BetterRTP/files/14470745/HolyWorldRtp-2.0.5.zip)

**Comment by SuperRonanCraft** [comment]
I and some other team members here were disrespected by the EngineHub's dev team, you can look them up, they are awful people.
Tried to recently update worldguard support, was basically told me to "Fuck off" so no I will not help in updating worldguard support. You can use older versions of worldguard till i believe v12 which is minecraft 1.13 or 1.14 when support was dropped, but anything else is not currently supported.

You can have someone else add support for recent versions, but none of our team members here at RonanServices will help.

We were thinking of entirely removing worldguard support due to EngineHub's behavior, but it would have been a disservice to current BetterRTP users.

**Comment by CatBoyTop2008** [comment]
> I and some other team members here were disrespected by the EngineHub's dev team, you can look them up, they are awful people. Tried to recently update worldguard support, was basically told me to "Fuck off" so no I will not help in updating worldguard support. You can use older versions of worldguard till i believe v12 which is minecraft 1.13 or 1.14 when support was dropped, but anything else is not currently supported.
> 
> You can have someone else add support for recent versions, but none of our team members here at RonanServices will help.
> 
> We were thinking of entirely removing worldguard support due to EngineHub's behavior, but it would have been a disservice to current BetterRTP users.

How does your relationship with the EngineHub studio team affect the fact that you cannot add support for random teleportation near regions? You just need to get the location of the region in the world (for example) and then check whether the player is a member or owner and if not teleport him to a distance from 50 to 150 blocks (for example)

**Comment by CatBoyTop2008** [comment]
Or am I missing something?
